/* eslint-disable camelcase */
import type { Agent, AgentList } from '~/app/agentsCatalogTypes';
import type { AgentsCatalogFilterOptionsList } from '~/app/pages/agentsCatalog/types/agentsCatalogFilterOptions';

export const mockAgent = (partial?: Partial<Agent>): Agent => ({
  id: '1',
  name: 'research-assistant',
  displayName: 'Research Assistant',
  description: 'An agent that performs research tasks using web search and summarization.',
  framework: 'LangGraph',
  source_id: 'sample',
  labels: ['Web search', 'General purpose'],
  logo: undefined,
  repositoryUrl: 'https://github.com/example/research-assistant',
  env: [{ name: 'OPENAI_API_KEY', required: true, description: 'API key for the LLM provider' }],
  artifacts: [{ uri: 'ghcr.io/example/research-assistant:latest' }],
  readme: '# Research Assistant\n\n### Overview\n\nAn agent for automated research.',
  ...partial,
});

export const mockAgentList = (partial?: Partial<AgentList>): AgentList => ({
  items: [mockAgent()],
  pageSize: 10,
  size: 1,
  nextPageToken: '',
  ...partial,
});

export const mockAgents: Agent[] = [
  mockAgent(),
  mockAgent({
    id: '2',
    name: 'code-reviewer',
    displayName: 'Code Reviewer',
    description: 'Automated code review agent using static analysis and LLMs.',
    framework: 'CrewAI',
    source_id: 'sample',
    labels: ['Tool use', 'General purpose'],
    repositoryUrl: 'https://github.com/example/code-reviewer',
    artifacts: [{ uri: 'ghcr.io/example/code-reviewer:latest' }],
  }),
  mockAgent({
    id: '3',
    name: 'data-pipeline-agent',
    displayName: 'Data Pipeline Agent',
    description: 'An agent that orchestrates data pipeline tasks.',
    framework: 'LangGraph',
    source_id: 'sample',
    labels: ['Deployment', 'Multi-agent'],
    readme: undefined,
  }),
];

export const mockAgentsGallery: Agent[] = [
  mockAgent({
    id: 'ga-1',
    name: 'web-researcher',
    displayName: 'Web Researcher',
    description: 'Searches the web, collects sources, and produces cited research summaries.',
    framework: 'LangGraph',
    source_id: 'community-agents',
    labels: ['Web search', 'General purpose'],
    logo: 'https://placekitten.com/32/32',
    env: [{ name: 'SERP_API_KEY', required: true, description: 'Search API key' }],
    artifacts: [{ uri: 'ghcr.io/agents/web-researcher:v1.2' }],
    readme: '# Web Researcher\nFull-featured web research agent.',
  }),
  mockAgent({
    id: 'ga-2',
    name: 'code-review-bot',
    displayName: 'Code Review Bot',
    description: 'Reviews pull requests for bugs, style issues, and security vulnerabilities.',
    framework: 'CrewAI',
    source_id: 'community-agents',
    labels: ['Tool use', 'General purpose'],
    artifacts: [{ uri: 'ghcr.io/agents/code-review-bot:latest' }],
  }),
  mockAgent({
    id: 'ga-3',
    name: 'data-etl-orchestrator',
    displayName: 'Data ETL Orchestrator',
    description: 'Orchestrates extract-transform-load pipelines across multiple data sources.',
    framework: 'Autogen',
    source_id: 'enterprise-agents',
    labels: ['Deployment', 'Multi-agent'],
    env: [
      { name: 'DB_CONNECTION', required: true, description: 'Database connection string' },
      { name: 'S3_BUCKET', required: false, description: 'Output S3 bucket' },
    ],
    artifacts: [{ uri: 'ghcr.io/agents/data-etl:v2.0' }],
    readme: '# Data ETL Orchestrator\nScalable ETL pipeline agent.',
  }),
  mockAgent({
    id: 'ga-4',
    name: 'translation-agent',
    displayName: 'Multi-Language Translator',
    description: 'Translates documents between 50+ languages with context awareness.',
    framework: 'Google ADK',
    source_id: 'community-agents',
    labels: ['General purpose', 'MCP'],
    logo: 'https://placekitten.com/33/33',
  }),
  mockAgent({
    id: 'ga-5',
    name: 'qa-test-generator',
    displayName: 'QA Test Generator',
    description: 'Generates test cases from requirements documents and user stories.',
    framework: 'CrewAI',
    source_id: 'enterprise-agents',
    labels: ['Tool use', 'Multi-agent'],
    env: [
      {
        name: 'JIRA_TOKEN',
        required: false,
        description: 'JIRA API token for ticket linking',
      },
    ],
    readme: '# QA Test Generator\nAutomated test generation from specs.',
  }),
  mockAgent({
    id: 'ga-6',
    name: 'devops-helper',
    displayName: 'DevOps Helper',
    description:
      'Assists with CI/CD pipeline configuration, deployment scripts, and monitoring setup.',
    framework: 'LangGraph',
    source_id: 'enterprise-agents',
    labels: ['Deployment', 'Tool use'],
    artifacts: [{ uri: 'ghcr.io/agents/devops-helper:v1.5' }],
  }),
  mockAgent({
    id: 'ga-7',
    name: 'security-scanner',
    displayName: 'Security Scanner Agent',
    description:
      'Scans codebases for vulnerabilities, outdated dependencies, and misconfigurations.',
    framework: 'Autogen',
    source_id: 'security-agents',
    labels: ['Tool use', 'Web search'],
    logo: 'https://placekitten.com/34/34',
    env: [
      { name: 'SNYK_TOKEN', required: true, description: 'Snyk API token' },
      { name: 'GH_TOKEN', required: true, description: 'GitHub token for repo access' },
    ],
    artifacts: [{ uri: 'ghcr.io/agents/security-scanner:v3.0' }],
    readme: '# Security Scanner\nComprehensive security analysis agent.',
  }),
  mockAgent({
    id: 'ga-8',
    name: 'monitoring-agent',
    displayName: 'Monitoring Dashboard Agent',
    description: 'Monitors system metrics and generates alerts based on anomaly detection.',
    framework: 'Claude Code',
    source_id: 'enterprise-agents',
    labels: ['Deployment', 'MCP'],
  }),
  mockAgent({
    id: 'ga-9',
    name: 'doc-writer',
    displayName: 'Documentation Writer',
    description: 'Generates API documentation, user guides, and changelogs from source code.',
    framework: 'LangGraph',
    source_id: 'community-agents',
    labels: ['General purpose', 'Tool use'],
    artifacts: [{ uri: 'ghcr.io/agents/doc-writer:latest' }],
    readme: '# Documentation Writer\nAuto-generate docs from code.',
  }),
  mockAgent({
    id: 'ga-10',
    name: 'incident-responder',
    displayName: 'Incident Responder',
    description: 'Triages production incidents, collects logs, and suggests remediation steps.',
    framework: 'CrewAI',
    source_id: 'security-agents',
    labels: ['Multi-agent', 'Deployment'],
    env: [{ name: 'PAGERDUTY_KEY', required: true, description: 'PagerDuty integration key' }],
  }),
  mockAgent({
    id: 'ga-11',
    name: 'meeting-summarizer',
    displayName: 'Meeting Summarizer',
    description: 'Transcribes and summarizes meetings, extracting action items and decisions.',
    framework: 'Google ADK',
    source_id: 'community-agents',
    labels: ['General purpose', 'Web search'],
    logo: 'https://placekitten.com/35/35',
  }),
  mockAgent({
    id: 'ga-12',
    name: 'custom-ml-trainer',
    displayName: 'Custom ML Trainer',
    description:
      'Fine-tunes machine learning models on custom datasets with hyperparameter tuning.',
    framework: 'A2A',
    source_id: 'ml-agents',
    labels: ['Deployment', 'Multi-agent'],
    env: [
      { name: 'WANDB_KEY', required: false, description: 'Weights & Biases API key' },
      { name: 'GPU_COUNT', required: false, description: 'Number of GPUs to use' },
    ],
    artifacts: [
      { uri: 'ghcr.io/agents/ml-trainer:v2.1' },
      { uri: 'ghcr.io/agents/ml-trainer-gpu:v2.1' },
    ],
    readme: '# Custom ML Trainer\nDistributed training with auto-tuning.',
  }),
  mockAgent({
    id: 'ga-13',
    name: 'sentiment-analyzer',
    displayName: 'Sentiment Analyzer',
    description: 'Analyzes customer feedback, reviews, and social media for sentiment trends.',
    framework: 'LangGraph',
    source_id: 'ml-agents',
    labels: ['General purpose', 'Web search'],
  }),
  mockAgent({
    id: 'ga-14',
    name: 'contract-reviewer',
    displayName: 'Contract Reviewer',
    description: 'Reviews legal contracts and highlights risks, obligations, and key clauses.',
    framework: 'Claude Code',
    source_id: 'enterprise-agents',
    labels: ['Tool use', 'General purpose'],
    logo: 'https://placekitten.com/36/36',
    readme: '# Contract Reviewer\nAI-powered legal contract analysis.',
  }),
  mockAgent({
    id: 'ga-15',
    name: 'chatbot-builder',
    displayName: 'Chatbot Builder',
    description: 'Creates conversational chatbots from knowledge bases and FAQ documents.',
    framework: 'Autogen',
    source_id: 'community-agents',
    labels: ['MCP', 'General purpose'],
    artifacts: [{ uri: 'ghcr.io/agents/chatbot-builder:latest' }],
  }),
  mockAgent({
    id: 'ga-16',
    name: 'log-analyzer',
    displayName: 'Log Analyzer',
    description: 'Parses application logs, identifies error patterns, and suggests fixes.',
    framework: 'LangGraph',
    source_id: 'security-agents',
    labels: ['Tool use', 'Deployment'],
    env: [{ name: 'ELASTIC_URL', required: true, description: 'Elasticsearch endpoint' }],
  }),
  mockAgent({
    id: 'ga-17',
    name: 'api-tester',
    displayName: 'API Tester',
    description: 'Generates and runs API test suites from OpenAPI specifications.',
    framework: 'CrewAI',
    source_id: 'enterprise-agents',
    labels: ['Tool use', 'MCP'],
    artifacts: [{ uri: 'ghcr.io/agents/api-tester:v1.0' }],
    readme: '# API Tester\nAutomatic API test generation from specs.',
  }),
  mockAgent({
    id: 'ga-18',
    name: 'model-evaluator',
    displayName: 'Model Evaluator',
    description: 'Evaluates ML model performance with automated benchmarks and bias detection.',
    framework: 'A2A',
    source_id: 'ml-agents',
    labels: ['Multi-agent', 'General purpose'],
    env: [{ name: 'MLFLOW_URI', required: false, description: 'MLflow tracking URI' }],
  }),
  mockAgent({
    id: 'ga-19',
    name: 'knowledge-graph-builder',
    displayName: 'Knowledge Graph Builder',
    description: 'Extracts entities and relationships from documents to build knowledge graphs.',
    framework: 'Google ADK',
    source_id: 'ml-agents',
    labels: ['Web search', 'General purpose'],
    logo: 'https://placekitten.com/37/37',
    artifacts: [{ uri: 'ghcr.io/agents/kg-builder:v1.3' }],
  }),
  mockAgent({
    id: 'ga-20',
    name: 'cost-optimizer',
    displayName: 'Cloud Cost Optimizer',
    description: 'Analyzes cloud spending and recommends cost-saving strategies across providers.',
    framework: 'Claude Code',
    source_id: 'enterprise-agents',
    labels: ['Deployment', 'Tool use'],
    env: [
      { name: 'AWS_ACCESS_KEY', required: true, description: 'AWS access key' },
      { name: 'GCP_SA_KEY', required: false, description: 'GCP service account key' },
    ],
    readme: '# Cloud Cost Optimizer\nMulti-cloud cost analysis and recommendations.',
  }),
];

export const mockAgentsCatalogFilterOptions = (
  partial?: Partial<AgentsCatalogFilterOptionsList>,
): AgentsCatalogFilterOptionsList => ({
  filters: {
    communicationProtocol: {
      type: 'string',
      values: ['A2A', 'Custom', 'MCP'],
    },
    framework: {
      type: 'string',
      values: ['A2A', 'Autogen', 'Claude Code', 'CrewAI', 'Google ADK', 'LangGraph'],
    },
    testedModels: {
      type: 'string',
      values: [
        'Anthropic-compatible endpoint',
        'Configurable',
        'OpenAI-compatible endpoint',
        'granite-3.1-8b-instruct',
      ],
    },
  },
  ...partial,
});
